#!/bin/bash

set -e
set -u
set -o pipefail

DISTS="trixie
latest
"
BASENAME=nishaero/minideb

if [ -n "${DOCKER_PASSWORD:-}" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
fi

push() {
    local dist="$1"
    docker push "${BASENAME}:${dist}"
}

for DIST in $DISTS; do
    push "$DIST"
done
